## Numpy Array and Basics

In [2]:
import numpy as np

### Creating Array From The List

In [3]:
arr_1 = np.array([1,2,3,4,5])
print(arr_1)

arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List Vs Numpy Array

In [4]:
pylist = [2,4,8]
print(pylist * 2)

ny1list = np.array([2,4,8])
print(ny1list * 2)

[2, 4, 8, 2, 4, 8]
[ 4  8 16]


### ZEROS AND ONES

In [5]:
zero = np.zeros((3,3))  #3,3 is 3 Rows and 3 Columns
print(zero)

ones = np.ones((2,3))
print(ones)

full = np.full((2,3), 5)
print(full)

randoms = np.random.random((2,3))
print(randoms)

sequece = np.arange(0,20,2)
print(sequece)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[0.66621522 0.62569379 0.86174672]
 [0.61201712 0.38606545 0.11781091]]
[ 0  2  4  6  8 10 12 14 16 18]


### Vector Matrix and Tensor

In [6]:
vect = np.array([1,2,3])
print(vect)

mat = np.array([[1,2,3,4],[5,6,7,8]])
print(mat)

ten = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(ten)

[1 2 3]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Types

In [7]:
arr = np.array([[1,False,3],
                [4.8,True,4]])

print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("Size",arr.size)
print("Data Type",arr.dtype)

## Any type of data fit but mostly use same data types


Shape (2, 3)
Dimension 2
Size 6
Data Type float64


### ARRAY Reshaped

In [16]:
arr = np.arange(12)

print(arr)

print(arp := arr.reshape(3,4))

flat = arp.flatten()
print(flat)

ravell = arp.ravel()
print(ravell)

#Transpose Method
tran = arp.T
print(tran)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
